version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/triagem-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/triagem-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/prontuario-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/prontuario-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/classificacao-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/classificacao-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
