apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: medsync
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: medsync
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
