apiVersion: v1
kind: Secret
metadata:
  name: classificacao-service-secret
  namespace: medsync
  labels:
    app.kubernetes.io/name: classificacao-service
    app.kubernetes.io/part-of: medsync
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg2://postgres:postgres@postgres-service:5432/classificacao_db"
  JWT_SECRET: "trocar-por-um-segredo-compartilhado-com-auth-service"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672/"
