sonar.organization=danielibatista
sonar.projectKey=danielibatista_triagem-final_prontuario-service
sonar.projectName=prontuario-service

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.10

