sonar.organization=danielibatista
sonar.projectKey=danielibatista_triagem-final_prontuario-service
sonar.projectName=prontuario-service

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__pycache__/**,**/*.pyc
sonar.coverage.exclusions=tests/**

