global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "triagem-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["d1:8000"]
  - job_name: "classificacao-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["d4:8000"]
  - job_name: "prontuario-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["d3:8000"]
