apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: medsync
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: medsync
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth-service
  ports:
    - name: http
      port: 8000
      targetPort: http
