apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prontuario-service
  namespace: medsync
  labels:
    app.kubernetes.io/name: prontuario-service
    app.kubernetes.io/part-of: medsync
spec:
  ingressClassName: nginx
  rules:
    - host: prontuario.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prontuario-service
                port:
                  name: http
