sonar.organization=danielibatista
sonar.projectKey=danielibatista_triagem-final_classificacao-service
sonar.projectName=classificacao-service

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml