apiVersion: v1
kind: Secret
metadata:
  name: triagem-service-secret
  namespace: medsync
  labels:
    app.kubernetes.io/name: triagem-service
    app.kubernetes.io/part-of: medsync
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg2://postgres:postgres@postgres-service:5432/triagem_db"
  JWT_SECRET: "trocar-por-um-segredo-compartilhado-com-auth-service"
